version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cqrs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cqrs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - cqrs-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cqrs_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  cqrs-network:
    driver: bridge 